main = "src/index.ts"

compatibility_date = "2024-05-30"

account_id = "3e4e267fb0f575f02c3d6ecd0c65f3cd"

name = "weather"
routes = ["weather.dstn.to/*"]
workers_dev = false

kv_namespaces = [
  { binding = "WEATHER_CACHE", id = "4c8cbf3bf02e429b8d59da44462be59f", preview_id = "ec15ecda849b45d7a1bd8ff482dffa6b" }
]

[env.dev]
name = "weather-dev"
routes = ["weather-dev.dstn.to/*"]
workers_dev = true

kv_namespaces = [
  { binding = "WEATHER_CACHE", id = "ec15ecda849b45d7a1bd8ff482dffa6b", preview_id = "ec15ecda849b45d7a1bd8ff482dffa6b" }
]